# Generated by Django 5.1.5 on 2025-05-10 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=50)),
                ('language', models.CharField(max_length=15)),
                ('duration', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
                ('showtimes', models.TimeField()),
                ('ticket_price', models.DecimalField(decimal_places=2, default=100.0, max_digits=6)),
            ],
        ),
    ]
