# Generated by Django 5.1.5 on 2025-06-02 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_movie_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='language',
            field=models.CharField(choices=[('Hindi', 'Hindi'), ('Nepali', 'Nepali'), ('English', 'English')], max_length=15),
        ),
    ]
