# Generated by Django 5.2 on 2025-05-13 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='SDsmbYTmADPwfKy4toTRdWsK7uUIUdo4', editable=False, max_length=32, unique=True),
        ),
    ]
