# Generated by Django 5.2 on 2025-05-13 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0002_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='FYs8qWk0ChlNWIZhqtOEhPTuKMyFbU2Q', editable=False, max_length=32, unique=True),
        ),
    ]
