# Generated by Django 5.2 on 2025-05-13 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0003_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='HAlMxkvdzYsejADXHSy3N1lLLgW9Dad0', editable=False, max_length=32, unique=True),
        ),
    ]
