# Generated by Django 5.2 on 2025-05-13 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0005_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='KZhzd66eL2ClIZML4rEoT0GwCZ2BJ1o1', editable=False, max_length=32, unique=True),
        ),
    ]
