# Generated by Django 5.2 on 2025-05-13 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0006_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_cashier',
            new_name='is_accountant',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='is_customer',
            new_name='is_client',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='R3yVCaMYz9lY0v7Nt0bLTJ9oN3Ecc4NM', editable=False, max_length=32, unique=True),
        ),
    ]
