# Generated by Django 5.2 on 2025-05-13 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0007_rename_is_cashier_customuser_is_accountant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='WJAoUODJ3ga8GLhoJ1Seiigv0aaV1kEj', editable=False, max_length=32, unique=True),
        ),
    ]
