# Generated by Django 5.2 on 2025-05-14 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0008_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='UuiB0J0Nc5lBRKWIINJWK23PoKntNsZt', editable=False, max_length=32, unique=True),
        ),
    ]
