# Generated by Django 5.1.5 on 2025-05-19 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0009_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='gbSLdYHa3h4XoLxLCzad6Ty8OMHbhsYW', editable=False, max_length=32, unique=True),
        ),
    ]
