# Generated by Django 5.1.5 on 2025-05-19 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0010_alter_customuser_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='B7we1wY3ATh5lhFcCck8G0LKYcWkV5k4', editable=False, max_length=32, unique=True),
        ),
    ]
