# Generated by Django 5.1.5 on 2025-05-19 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0011_alter_customuser_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='syGyFv15sZAgWbLDYThtXqLqYS4i8K8g', editable=False, max_length=32, unique=True),
        ),
    ]
