# Generated by Django 5.1.5 on 2025-05-19 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0012_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='a7zdDz63cwiFK25mQywv9ygGWVF62yFm', editable=False, max_length=32, unique=True),
        ),
    ]
