# Generated by Django 5.1.5 on 2025-05-23 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0013_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='gmefHrC8fZH7YyrzBP8OkzG4jKg6ctPG', editable=False, max_length=32, unique=True),
        ),
    ]
