# Generated by Django 5.1.5 on 2025-05-23 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0014_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='hWuQ9krf8HjjTIsxQWDmWPD8lBar0KYH', editable=False, max_length=32, unique=True),
        ),
    ]
