# Generated by Django 5.2 on 2025-05-29 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0015_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='1lEg9geSrqyDiTuLKMlrqOYds9JaPCSG', editable=False, max_length=32, unique=True),
        ),
    ]
