# Generated by Django 5.2 on 2025-05-29 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0017_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='IIexdCJlBPEbkfik1uLhtlikf95tLkaY', editable=False, max_length=32, unique=True),
        ),
    ]
