# Generated by Django 5.1.5 on 2025-06-02 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0018_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='xvzJVBAoB3c13Jh1lZRU4wBmhGMcth33', editable=False, max_length=32, unique=True),
        ),
    ]
