# Generated by Django 5.1.5 on 2025-06-08 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0019_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='9R43bCGcAWtwKQwqm5yrHNa62N8OnlgH', editable=False, max_length=32, unique=True),
        ),
    ]
