# Generated by Django 5.1.5 on 2025-06-10 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0021_remove_customuser_is_accountant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='I28n436t8aj2bjzwLMgPnVc8mGXE9M88', editable=False, max_length=32, unique=True),
        ),
    ]
