# Generated by Django 5.1.5 on 2025-06-10 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0022_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='m6FksFgkGI9zaLkE4W4FdOHscc5wm8JH', editable=False, max_length=32, unique=True),
        ),
    ]
