# Generated by Django 5.1.5 on 2025-06-10 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0024_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('admin', 'Admin')], default='customer', max_length=10),
        ),
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='VWnO0ASFFGsG7tI5UpbyESgF6w6EOu1Y', editable=False, max_length=32, unique=True),
        ),
    ]
