# Generated by Django 5.1.5 on 2025-06-10 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0025_customuser_role_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('admin', 'Admin')], max_length=10),
        ),
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='KzZgCEsAx0fFBEjoIYiV5Er4inPheeGv', editable=False, max_length=32, unique=True),
        ),
    ]
