# Generated by Django 5.1.5 on 2025-06-10 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0026_alter_customuser_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='0KZMLnd8X340G1OBZVrLZcqOguE8O58b', editable=False, max_length=32, unique=True),
        ),
    ]
