# Generated by Django 5.1.5 on 2025-06-10 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0027_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='wo4rSFNQBA3K14sfbrvxiK6pGqu7vURO', editable=False, max_length=32, unique=True),
        ),
    ]
