# Generated by Django 5.1.5 on 2025-06-10 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0028_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='confirm_password',
            field=models.CharField(default='Hastabir@123', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='46K1099zRWAFiSPw42b24lIEILKOnr4i', editable=False, max_length=32, unique=True),
        ),
    ]
