# Generated by Django 5.1.5 on 2025-06-10 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0029_customuser_confirm_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='7nldNGqJvcG6oQ3XZK8lc7SZQJFQL1WR', editable=False, max_length=32, unique=True),
        ),
    ]
