# Generated by Django 5.1.5 on 2025-06-10 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0031_alter_customuser_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='3tZjlZzjEhpcmuYvW2bE1uqPX7YjsAM4', editable=False, max_length=32, unique=True),
        ),
    ]
