# Generated by Django 5.1.5 on 2025-06-10 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0032_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='XYvyBGK2tiAQA9N7c9JGXEIvqKTnWrIW', editable=False, max_length=32, unique=True),
        ),
    ]
