# Generated by Django 5.1.5 on 2025-06-11 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0035_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='mdFOJhr7cmvI3WwLhoBtOYLXFKPu39dN', editable=False, max_length=32, unique=True),
        ),
    ]
