# Generated by Django 5.1.5 on 2025-06-11 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0036_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='nXrr0g48tttx3YkawRB2B3nl7WrYeWP4', editable=False, max_length=32, unique=True),
        ),
    ]
