# Generated by Django 5.1.5 on 2025-06-11 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0037_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='2vOuDzq0uEGX9t8uB7g2xwFZvhPEFEsO', editable=False, max_length=32, unique=True),
        ),
    ]
