# Generated by Django 5.1.5 on 2025-06-11 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0038_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='pfvE1sLMxsqx4iF518vEzhb7bZEiH1Ss', editable=False, max_length=32, unique=True),
        ),
    ]
