# Generated by Django 5.1.5 on 2025-06-11 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0039_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='g8KyT4lMSMTenggcfNv6yzpyV0VEsqtk', editable=False, max_length=32, unique=True),
        ),
    ]
