# Generated by Django 5.1.5 on 2025-06-11 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0041_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='QMs6WaZ7VyMKKtxPCEQf2IpyklAfjpJa', editable=False, max_length=32, unique=True),
        ),
    ]
