# Generated by Django 4.2.30 on 2026-05-26 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0043_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='23d0i6XGFk61Nduitx69xFzuKAYUY7ij', editable=False, max_length=32, unique=True),
        ),
    ]
