# Generated by Django 5.1.5 on 2025-05-19 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='book',
            name='per_ticket_price',
            field=models.IntegerField(default=400.0),
        ),
        migrations.AddField(
            model_name='book',
            name='phone',
            field=models.CharField(default='0000000000', max_length=100),
        ),
        migrations.AddField(
            model_name='book',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='book',
            name='ticket_price',
            field=models.DecimalField(decimal_places=2, default=400.0, max_digits=6),
        ),
    ]
