# Generated by Django 5.2 on 2025-05-29 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0002_remove_book_phone_number_book_per_ticket_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='seats',
            field=models.IntegerField(max_length=100),
        ),
    ]
